Add files via upload
named-entity/nltk4russian pull request #1
Opened 2019-01-15 13:41 UTC by vadim0006

2019-01-15 14:50 UTC, named-entity requested changes

2019-01-15 14:50 UTC, named-entity commented on tutorials/Affix tagger.ipynb
> +    "with open('media_train.tab', encoding = 'utf-8', mode='r') as f:\n",
media_train и media_test это случайно не какие-то из файлов media в https://github.com/named-entity/nltk4russian/tree/master/data?

2019-01-15 15:15 UTC, vadim0006 commented on tutorials/Affix tagger.ipynb
> +    "with open('media_train.tab', encoding = 'utf-8', mode='r') as f:\n",
Да, это все три объединенные и поделенные в пропорциях 80 / 20

2019-01-15 16:11 UTC, named-entity commented on tutorials/Affix tagger.ipynb
> +    "with open('media_train.tab', encoding = 'utf-8', mode='r') as f:\n",
Давайте их тогда положим в nltk4russian/data и в коде исправим путь на "../data/media_train.tab" и "../data/media_test.tab"

2019-01-16 13:16 UTC, vadim0006 commented on tutorials/Affix tagger.ipynb
> +    "with open('media_train.tab', encoding = 'utf-8', mode='r') as f:\n",
Сделал!

2019-01-16 13:24 UTC, named-entity approved these changes

2019-01-16 13:24 UTC, merged